INSERT INTO students (STUDENT_NUMBER, STUDENT_NAME, STUDENT_SURNAME, STUDENT_EMAIL) VALUES (1111111, 'SName1', 'SSurname1', 'SName1.SSurname1@fri.uni-lj.si');
INSERT INTO students (STUDENT_NUMBER, STUDENT_NAME, STUDENT_SURNAME, STUDENT_EMAIL) VALUES (2222222, 'SName2', 'SSurname2', 'SName2.SSurname2@fri.uni-lj.si');
INSERT INTO students (STUDENT_NUMBER, STUDENT_NAME, STUDENT_SURNAME, STUDENT_EMAIL) VALUES (3333333, 'SName3', 'SSurname3', 'SName3.SSurname3@fri.uni-lj.si');
INSERT INTO students (STUDENT_NUMBER, STUDENT_NAME, STUDENT_SURNAME, STUDENT_EMAIL) VALUES (4444444, 'SName4', 'SSurname4', 'SName4.SSurname4@fri.uni-lj.si');
INSERT INTO students (STUDENT_NUMBER, STUDENT_NAME, STUDENT_SURNAME, STUDENT_EMAIL) VALUES (5555555, 'SName5', 'SSurname5', 'SName5.SSurname5@fri.uni-lj.si');
INSERT INTO students (STUDENT_NUMBER, STUDENT_NAME, STUDENT_SURNAME, STUDENT_EMAIL) VALUES (6666666, 'SName6', 'SSurname6', 'SName6.SSurname6@fri.uni-lj.si');

INSERT INTO professors (PROFESSOR_NAME, PROFESSOR_SURNAME, PROFESSOR_EMAIL) VALUES ('PName1', 'PSurname1', 'PName1.PSurname1@fri.uni-lj.si');
INSERT INTO professors (PROFESSOR_NAME, PROFESSOR_SURNAME, PROFESSOR_EMAIL) VALUES ('PName2', 'PSurname2', 'PName2.PSurname2@fri.uni-lj.si');
INSERT INTO professors (PROFESSOR_NAME, PROFESSOR_SURNAME, PROFESSOR_EMAIL) VALUES ('PName3', 'PSurname3', 'PName3.PSurname3@fri.uni-lj.si');
INSERT INTO professors (PROFESSOR_NAME, PROFESSOR_SURNAME, PROFESSOR_EMAIL) VALUES ('PName4', 'PSurname4', 'PName4.PSurname4@fri.uni-lj.si');
INSERT INTO professors (PROFESSOR_NAME, PROFESSOR_SURNAME, PROFESSOR_EMAIL) VALUES ('PName5', 'PSurname5', 'PName5.PSurname5@fri.uni-lj.si');
INSERT INTO professors (PROFESSOR_NAME, PROFESSOR_SURNAME, PROFESSOR_EMAIL) VALUES ('PName6', 'PSurname6', 'PName6.PSurname6@fri.uni-lj.si');
INSERT INTO professors (PROFESSOR_NAME, PROFESSOR_SURNAME, PROFESSOR_EMAIL) VALUES ('PName7', 'PSurname7', 'PName7.PSurname7@fri.uni-lj.si');

INSERT INTO topics (TOPIC_TITLE, TOPIC_DESCRIPTION, AUTHOR_ID) VALUES ('TTitle1', 'TDescription1', 1);
INSERT INTO topics (TOPIC_TITLE, TOPIC_DESCRIPTION, AUTHOR_ID) VALUES ('TTitle2', 'TDescription2', 2);
INSERT INTO topics (TOPIC_TITLE, TOPIC_DESCRIPTION, AUTHOR_ID) VALUES ('TTitle3', 'TDescription3', 3);
INSERT INTO topics (TOPIC_TITLE, TOPIC_DESCRIPTION, AUTHOR_ID) VALUES ('TTitle4', 'TDescription4', 4);
INSERT INTO topics (TOPIC_TITLE, TOPIC_DESCRIPTION, AUTHOR_ID) VALUES ('TTitle5', 'TDescription5', 5);
INSERT INTO topics (TOPIC_TITLE, TOPIC_DESCRIPTION, AUTHOR_ID) VALUES ('TTitle6', 'TDescription6', 6);
INSERT INTO topics (TOPIC_TITLE, TOPIC_DESCRIPTION, AUTHOR_ID) VALUES ('TTitle7', 'TDescription7', 3);
INSERT INTO topics (TOPIC_TITLE, TOPIC_DESCRIPTION, AUTHOR_ID) VALUES ('TTitle8', 'TDescription8', 4);
INSERT INTO topics (TOPIC_TITLE, TOPIC_DESCRIPTION, AUTHOR_ID) VALUES ('TTitle9', 'TDescription9', 4);

INSERT INTO applied_students(STUDENT_ID, TOPIC_ID) VALUES(1, 2);
INSERT INTO applied_students(STUDENT_ID, TOPIC_ID) VALUES(1, 3);
INSERT INTO applied_students(STUDENT_ID, TOPIC_ID) VALUES(1, 4);
INSERT INTO applied_students(STUDENT_ID, TOPIC_ID) VALUES(2, 1);
INSERT INTO applied_students(STUDENT_ID, TOPIC_ID) VALUES(2, 2);
INSERT INTO applied_students(STUDENT_ID, TOPIC_ID) VALUES(3, 3);
INSERT INTO applied_students(STUDENT_ID, TOPIC_ID) VALUES(3, 4);
INSERT INTO applied_students(STUDENT_ID, TOPIC_ID) VALUES(3, 5);
INSERT INTO applied_students(STUDENT_ID, TOPIC_ID) VALUES(4, 1);