kumuluzee:
  name: prpoVaje03
  version: 1.0.0
  env:
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
      - jndi-name: jdbc/uporabniki
        connection-url: jdbc:postgresql://localhost:5439/uporabniki
        username: postgres
        password: postgres
        max-pool-size: 20