kumuluzee:
  name: prpoVaje03
  version: 1.0.0
  env:
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/uporabniki
      connection-url: jdbc:postgresql://localhost:5439/uporabniki
      username: postgres
      password: postgres
      max-pool-size: 20
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 30
    ping-interval: 5
  health:
    checks:
      etcd-health-check:
        connection-url: http://localhost:2379/health
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/uporabniki
